# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vocab.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vocab.proto',
  package='cta',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bvocab.proto\x12\x03\x63ta\".\n\x0cVocabularies\x12\x1e\n\x0bknown_words\x18\x01 \x03(\x0b\x32\t.cta.Word\">\n\x04Word\x12\x11\n\thead_word\x18\x01 \x01(\t\x12\x0e\n\x06pinyin\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65\x66initions\x18\x03 \x03(\tb\x06proto3'
)




_VOCABULARIES = _descriptor.Descriptor(
  name='Vocabularies',
  full_name='cta.Vocabularies',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='known_words', full_name='cta.Vocabularies.known_words', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=66,
)


_WORD = _descriptor.Descriptor(
  name='Word',
  full_name='cta.Word',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='head_word', full_name='cta.Word.head_word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pinyin', full_name='cta.Word.pinyin', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='definitions', full_name='cta.Word.definitions', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=130,
)

_VOCABULARIES.fields_by_name['known_words'].message_type = _WORD
DESCRIPTOR.message_types_by_name['Vocabularies'] = _VOCABULARIES
DESCRIPTOR.message_types_by_name['Word'] = _WORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vocabularies = _reflection.GeneratedProtocolMessageType('Vocabularies', (_message.Message,), {
  'DESCRIPTOR' : _VOCABULARIES,
  '__module__' : 'vocab_pb2'
  # @@protoc_insertion_point(class_scope:cta.Vocabularies)
  })
_sym_db.RegisterMessage(Vocabularies)

Word = _reflection.GeneratedProtocolMessageType('Word', (_message.Message,), {
  'DESCRIPTOR' : _WORD,
  '__module__' : 'vocab_pb2'
  # @@protoc_insertion_point(class_scope:cta.Word)
  })
_sym_db.RegisterMessage(Word)


# @@protoc_insertion_point(module_scope)
