version: "3"

services:
    nginx:
        image: nginx:latest
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/:/etc/nginx/
        - ./nginx/cache/:/etc/nginx/cache
        - /etc/letsencrypt/:/etc/letsencrypt/
        ports:
        - 80:80
        - 443:443
    anki-sync-server:
      # container_name: anki-sync-server
        image: kuklinistvan/anki-sync-server:latest
        restart: always
        expose:
        - 27701
        volumes:
        - ./data:/app/data
    cta:
        image: httpd:2.4
        restart: always
        expose:
        - 80 
        volumes:
         - ./httpd:/usr/local/apache2/htdocs/ 
    home:
        image: nginx:latest
        restart: always
        expose:
          - 80

